bb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path('rosetta/', include('rosetta.urls')),
    path('', include('girls.urls', namespace='girls')),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

girls/urls.py
from django.urls import path
from . import views

app_name = 'girls'

urlpatterns = [
    path('', views.home, name='home'),
    path('set-city/', views.city, name='city'),
    path('catalog/', views.catalog, name='catalog'),
    path('catalog/<slug:slug>/', views.catalog, name='catalog_by_slug'),
    path('search/', views.search, name='search'),
    path('by-service/<slug:slug>/', views.catalog_by_service, name='catalog_by_service'),
    path('by-real-photo/', views.catalog_real_photo, name='catalog_by_real_photo'),
    path('by-outcall/', views.catalog_outcall, name='catalog_by_outcall'),
    path('by-apartment/', views.catalog_apartment, name='catalog_by_apartment'),
    path('girl/<int:id>/', views.girl_detail, name='girl'),
    path('girl/<int:id>/add-review/', views.girl_add_review, name='add_review'),
    path('girl/<int:girl_id>/detele-review/<int:review_id>/', views.girl_delete_review, name='delete_review'),
    path('girl/<int:girl_id>/update-video-cnt/', views.girl_update_video_cnt, name='update_video_cnt'),
]

girls/forms.py
from django import forms
from .models import Review
from girls.models import City, Girl
from django.utils.translation import gettext_lazy as _


class AddReviewForm(forms.ModelForm):
    name = forms.CharField(label=False,
                           max_length=100,
                           widget=forms.TextInput(attrs={
                               'placeholder': _('Name*'),
                           }))
    phone = forms.CharField(label=False,
                            max_length=30,
                            widget=forms.TextInput(attrs={
                                'type': 'tel',
                                'placeholder': _('Phone*')
                            }))
    body = forms.CharField(label=False,
                           max_length=400,
                           widget=forms.Textarea(
                               attrs={
                                   'placeholder': _('Review*')
                               }
                           ))

    class Meta:
        model = Review
        fields = ('name', 'phone', 'body')


class SearchForm(forms.Form):
    # city = forms.ModelChoiceField(queryset=City.objects.all(),
    #                               label=_('City'),
    #                               required=False)
    age = forms.ChoiceField(label=_('Age'),
                            required=False)
    price_from = forms.IntegerField(min_value=0,
                                    label=_('Min price'),
                                    required=False)
    price_to = forms.IntegerField(min_value=0,
                                  label=_('Max price'),
                                  required=False)
    apartments = forms.BooleanField(required=False,
                                    label=_('Apartments'),
                                    widget=forms.CheckboxInput)
    arrive = forms.BooleanField(required=False,
                                label=_('Departure'),
                                widget=forms.CheckboxInput)
    search = forms.CharField(widget=forms.HiddenInput(attrs={'value': 'search'}))

    def __init__(self, *args, **kwargs):
        """Adding choices for age"""
        super(SearchForm, self).__init__(*args, **kwargs)
        choices = []
        ages = Girl.published.all().values_list('age', 'age').distinct()
        for age in ages:
            choices.append(tuple(age))
        choices.sort(key=lambda x:x[0])
        choices = [('', '---------')] + choices
        self.fields['age'].choices = choices

girls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Girl, Image, Review, View, Video, Service
from .forms import AddReviewForm
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from rates.models import Category, Rate
from .forms import SearchForm
from .utils import filter_by_city, get_current_city
from random import shuffle
from django.db.models import F
import datetime
from django.utils.translation import gettext_lazy as _


def home(request):
    # today = datetime.datetime.today().date()
    # end_date = datetime.date(year=2022, month=2, day=22)
    # if today > end_date:
    #     return render(request, 'list.html', {})
    girls_object = Girl.published.all().order_by('-created')
    girls_object = filter_by_city(request, girls_object)
    slug = 'new'
    category_name = 'Новые | New | חָדָשׁ'
    paginator = Paginator(girls_object, 15)
    page = request.GET.get('page')
    try:
        girls = paginator.page(page)
    except PageNotAnInteger:
        girls = paginator.page(1)
    except EmptyPage:
        girls = paginator.page(paginator.num_pages)

    lux_tariffs = Rate.objects.filter(type='lux')
    lux_tariffs = list(rate.id for rate in lux_tariffs)
    lux_girls = Girl.published.filter(rate_id__in=lux_tariffs)
    lux_girls = filter_by_city(request, lux_girls)
    context = {
        'category_name': category_name,
        'lux_girls': lux_girls,
        'slug': slug,
        'girls': girls,
        'section': 'home'
    }
    return render(request, 'pages/home.html', context)


def girl_detail(request, id):
    girl = get_object_or_404(Girl, id=id)
    if girl.max_images == -1:
        photos = Image.objects.filter(girl=girl)
    else:
        photos = Image.objects.filter(girl=girl)[:girl.max_images]
    if girl.max_videos == -1:
        videos = Video.objects.filter(girl=girl)
    else:
        videos = Video.objects.filter(girl=girl)[:girl.max_videos]
    reviews_objects = girl.reviews.all().order_by('-created')
    paginator = Paginator(reviews_objects, 12)
    page = request.GET.get('page')
    try:
        reviews = paginator.page(page)
    except PageNotAnInteger:
        reviews = paginator.page(1)
    except EmptyPage:
        reviews = paginator.page(paginator.num_pages)

    add_review_form = AddReviewForm()
    if (request.user.is_authenticated and request.user.girl != girl) or not request.user.is_authenticated:
        View.objects.create(type='profile', profile=girl)
    related_girls = list(Girl.published.exclude(id=girl.id).filter(city=girl.city)[:10])
    shuffle(related_girls)
    context = {
        'girl': girl,
        'photos': photos,
        'videos': videos,
        'reviews': reviews,
        'add_review_form': add_review_form,
        'related_girls': related_girls
    }
    return render(request, 'girls/girl_detail.html', context)


@require_POST
def girl_add_review(request, id):
    add_review_form = AddReviewForm(request.POST)
    if add_review_form.is_valid():
        review = add_review_form.save(commit=False)
        girl = get_object_or_404(Girl, id=id)
        review.girl = girl
        review.save()
        return JsonResponse({'status': 'ok'})
    else:
        return JsonResponse({'status': 'bad'})


@require_POST
@login_required
def girl_delete_review(request, girl_id, review_id):
    girl = request.user.girl
    if not girl.can_delete_comments:
        return JsonResponse({'status': 'bad'})
    review = get_object_or_404(Review, pk=review_id)
    if review.girl == girl:
        review.delete()
        return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'bad'})


@require_POST
def girl_update_video_cnt(request, girl_id):
    girl = get_object_or_404(Girl, id=girl_id)
    if request.user.is_authenticated and request.user.girl != girl or not request.user.is_authenticated:
        View.objects.create(profile=girl, type='video')
        return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'bad'})


def catalog(request, slug=None):
    girls_object = Girl.published.all().order_by('-created')
    girls_object = filter_by_city(request, girls_object)
    if slug:
        category = get_object_or_404(Category, slug=slug)
        rates = Rate.objects.filter(category=category)
        girls_object = girls_object.filter(rate__in=rates)
        category_name = category.name
    else:
        slug = 'new'
        category_name = 'Новые | New | חָדָשׁ'

    force_girls_list = None
    if girls_object.count() > 20:
        force_girls_list = list(girls_object.filter(active_advertising=True, adds_left__gt=0))
        shuffle(force_girls_list)
        force_girls_list = force_girls_list[:10]
        force_girls_ids = list(girl.id for girl in force_girls_list)
        girls_object = girls_object.exclude(id__in=force_girls_ids)
        if not request.user.is_authenticated:
            for force_girl in force_girls_list:
                force_girl.adds_left = F('adds_left') - 1
                force_girl.save()
    paginator = Paginator(girls_object, 15)
    page = request.GET.get('page')
    try:
        girls = paginator.page(page)
    except PageNotAnInteger:
        girls = paginator.page(1)
    except EmptyPage:
        girls = paginator.page(paginator.num_pages)
    context = {
        'category_name': category_name,
        'slug': slug,
        'girls': girls,
        'force_girls_list': force_girls_list,
        'section': 'catalog'
    }
    return render(request, 'pages/catalog.html', context)


def search(request):
    search_form = SearchForm(request.GET)
    is_searching = False
    girls = False
    if search_form.is_valid():
        cd = search_form.cleaned_data
        girls_object = Girl.published.all().order_by('-created')
        girls_object = filter_by_city(request, girls_object)
        if cd['age']:
            girls_object = girls_object.filter(age=cd['age'])
        if cd['price_from']:
            girls_object = girls_object.filter(min_price__gte=int(cd['price_from']))
        if cd['price_to']:
            girls_object = girls_object.filter(max_price__lte=int(cd['price_to']))
        if cd['apartments']:
            girls_object = girls_object.filter(apartment=True)
        if cd['arrive']:
            girls_object = girls_object.filter(arrive=True)
        if cd['search']:
            is_searching = True
        paginator = Paginator(girls_object, 15)
        page = request.GET.get('page')
        try:
            girls = paginator.page(page)
        except PageNotAnInteger:
            girls = paginator.page(1)
        except EmptyPage:
            girls = paginator.page(paginator.num_pages)

    context = {
        'is_searching': is_searching,
        'girls': girls,
        'search_form': search_form
    }
    return render(request, 'pages/search.html', context)


@require_POST
def city(request):
    request.session['city'] = request.POST.get('slug')
    return JsonResponse({'status': 'ok'})


def catalog_by_service(request, slug):
    service = get_object_or_404(Service, slug=slug)
    girls_object = Girl.published.all().order_by('-created')
    girls_object = filter_by_city(request, girls_object)
    girls_object = girls_object.filter(services=service)
    category_name = service.name
    force_girls_list = None
    if girls_object.count() > 20:
        force_girls_list = list(girls_object.filter(active_advertising=True, adds_left__gt=0))
        shuffle(force_girls_list)
        force_girls_list = force_girls_list[:10]
        force_girls_ids = list(girl.id for girl in force_girls_list)
        girls_object = girls_object.exclude(id__in=force_girls_ids)
        if not request.user.is_authenticated:
            for force_girl in force_girls_list:
                force_girl.adds_left = F('adds_left') - 1
                force_girl.save()
    paginator = Paginator(girls_object, 15)
    page = request.GET.get('page')
    try:
        girls = paginator.page(page)
    except PageNotAnInteger:
        girls = paginator.page(1)
    except EmptyPage:
        girls = paginator.page(paginator.num_pages)

    context = {
        'category_name': category_name,
        'slug': slug,
        'girls': girls,
        'force_girls_list': force_girls_list,
        'section': 'catalog'
    }
    return render(request, 'pages/catalog.html', context)


def catalog_real_photo(request):
    girls_object = Girl.published.all().order_by('-created')
    girls_object = filter_by_city(request, girls_object)
    girls_object = girls_object.filter(verified=True)
    category_name = _('Real photo')
    force_girls_list = None
    if girls_object.count() > 20:
        force_girls_list = list(girls_object.filter(active_advertising=True, adds_left__gt=0))
        shuffle(force_girls_list)
        force_girls_list = force_girls_list[:10]
        force_girls_ids = list(girl.id for girl in force_girls_list)
        girls_object = girls_object.exclude(id__in=force_girls_ids)
        if not request.user.is_authenticated:
            for force_girl in force_girls_list:
                force_girl.adds_left = F('adds_left') - 1
                force_girl.save()
    paginator = Paginator(girls_object, 15)
    page = request.GET.get('page')
    try:
        girls = paginator.page(page)
    except PageNotAnInteger:
        girls = paginator.page(1)
    except EmptyPage:
        girls = paginator.page(paginator.num_pages)
    slug = 'real-photo'
    context = {
        'category_name': category_name,
        'slug': 'by-real-photo',
        'girls': girls,
        'force_girls_list': force_girls_list,
        'section': 'catalog',
        'slug': slug
    }
    return render(request, 'pages/catalog.html', context)


def catalog_outcall(request):
    girls_object = Girl.published.all().order_by('-created')

girls/templates/girls/girl_detail.html
{% extends 'layout/base.html' %}
{% load bb_tags %}
{% load static %}
{% load thumbnail %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load lang_tags %}

{% block title %}{{ girl.name }}{% endblock %}

{% block content %}
<main class="single">
    <div class="container">
        <div class="single-row">
            <div class="single-galleries" dir="ltr">
                {% if photos or videos %}
                <div class="single-gallery">
                    {% for photo in photos %}
                    <div class="single-gallery__item">
                        <div class="thumb">
                            <img src="{{ photo.file|thumbnail_url:'medium' }}">
                        </div>
                    </div>
                    {% endfor %}
                    {% for video in videos %}
                    <div class="single-gallery__item">
                        <div class="thumb">
                            <video src="{{ video.file.url }}" controls
                                   data-action="{% url 'girls:update_video_cnt' girl.id %}">
                            </video>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- /.single-gallery -->
                <div class="single-subgallery">
                    {% for photo in photos %}
                    <div class="single-subgallery__item">
                        <div class="thumb">
                            <img src="{{ photo.file|thumbnail_url:'small' }}">
                        </div>
                    </div>
                    {% endfor %}
                    {% for video in videos %}
                    <div class="single-subgallery__item">
                        <div class="thumb">
                            <video src="{{ video.file.url }}"></video>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- /.single-subgallery -->
                {% endif %}
            </div>
            <!-- /.single-subgalleries -->
            <div class="single-info">
                {% if girl.name %}
                    <h1 class="single__title">{{ girl.name }}</h1>
                {% endif %}
                <ul class="single__params single-params">
                    {% if girl.age %}
                    <li class="single-params__item">
                        <span class="label">{% trans 'Age' %}</span>
                        <strong class="value">{{ girl.age }}</strong>
                    </li>
                    {% endif %}
                    {% if girl.breast %}
                    <li class="single-params__item">
                        <span class="label">{% trans 'Breast' %}</span>
                        <strong class="value">{{ girl.breast }}</strong>
                    </li>
                    {% endif %}
                    {% if girl.growth %}
                    <li class="single-params__item">
                        <span class="label">{% trans 'Height' %}</span>
                        <strong class="value">{{ girl.growth }}</strong>
                    </li>
                    {% endif %}
                    {% if girl.weight %}
                    <li class="single-params__item">
                        <span class="label">{% trans 'Weight' %}</span>
                        <strong class="value">{{ girl.weight }}</strong>
                    </li>
                    {% endif %}
                </ul>
                <ul class="socials">
                    {% if girl.whatsapp %}
                    <li class="socials__item socials-item">
                        <a class="socials-item__link" target="_blank" href="{{ girl.whatsapp|whatsapp }}" aria-label="вотсап">
                            <img class="socials-item__img" src="{% static 'img/icon-whatsapp.png' %}" alt="вотсап">
                        </a>
                    </li>
                    {% endif %}
                    {% if girl.telegram %}
                    <li class="socials__item socials-item">
                        <a class="socials-item__link" target="_blank" href="{{ girl.telegram }}" aria-label="телеграм">
                            <img class="socials-item__img" src="{% static 'img/icon-telegram.png' %}" alt="телеграм">
                        </a>
                    </li>
                    {% endif %}
                    {% if girl.phone %}
                    <li class="socials__item socials-item">
                        <a class="socials-item__link" href="{{ girl.phone|phone_to_link }}" aria-label="телефон">
                            <img class="socials-item__img" src="{% static 'img/icon-phone.png' %}" alt="телефон">
                            <span class="socials-item__text">{{ girl.phone|phone_clear }}</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <!-- /.socials -->
                {% if girl.about %}
                <div class="single-about single__about">
                    <h2 class="single-subtitle">{% trans 'About me:' %}</h2>
                    <div class="single-about__desc">
                        {{ girl.about|linebreaks }}
                    </div>
                </div>
                {% endif %}
                {% with girl.services.all as services %}
                    {% if services %}
                    <div class="single-services">
                        <h2 class="single-subtitle">{% trans 'Services:' %}</h2>
                        <ul class="services-group">
                            {% for service in services %}
                                <li class="services-group__item">{{ service.name|translate:LANGUAGE_CODE }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- /.single-services -->
                    {% endif %}
                {% endwith %}
                <div class="single-cost">
                    <h2 class="single-subtitle">{% trans 'Price' %}</h2>
                    <table class="single-cost__table cost-table">
                        <thead>
                            <tr>
                                <td></td>
                                <td>{% trans 'Apartments' %}</td>
                                <td>{% trans 'Departure' %}</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{% trans '30 minutes' %}</td>
                                <td>{% firstof girl.price_30_home '----' %} ₪</td>
                                <td>---- ₪</td>
                            </tr>
                            <tr>
                                <td>{% trans '1 hour' %}</td>
                                <td>{% firstof girl.price_1h_home '----' %} ₪</td>
                                <td>{% firstof girl.price_1h_departure '----' %} ₪</td>
                            </tr>
                            <tr>
                                <td>{% trans '2 hours' %}</td>
                                <td>{% firstof girl.price_2h_home '----' %} ₪</td>
                                <td>{% firstof girl.price_2h_departure '----' %} ₪</td>
                            </tr>
                            <tr>
                                <td>{% trans 'night' %}</td>
                                <td>{% firstof girl.price_night_home '----' %} ₪</td>
                                <td>{% firstof girl.price_night_departure '----' %} ₪</td>
                            </tr>
                        </tbody>
                    </table>
                    <ul class="single-cost__adds single-adds">
                        {% if girl.parking %}
                        <li class="single-adds__item adds-item">
                            <div class="thumb">
                                <img src="{% static 'img/icon-parking.png' %}" alt="маркер">
                            </div>
                            <div class="adds-item__text">{% trans 'There is parking' %}</div>
                        </li>
                        {% endif %}
                        {% if girl.apartment %}
                        <li class="single-adds__item">
                            <div class="thumb">
                                <img src="{% static 'img/icon-checked-rounded.png' %}" alt="маркер">
                            </div>
                            <div class="adds-item__text">{% trans 'Discrete flat' %}</div>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <!-- /.single-cost -->
                <div class="single-add-review">
                    <button class="btn btn_secondary" type="button">{% trans 'Leave Review' %}</button>
                </div>
            </div>
            <!-- /.single-info -->
        </div>
    </div>
</main>
<!-- /.single -->

{% include 'girls/partials/reviews.html' %}

{% include 'girls/partials/related_girls.html' %}

{% if girl.status == 'disabled' %}
<div class="popup" style="display:block;">
    {% include 'girls/forms/disabled-form.html' %}
</div>
{% else %}
<div class="popup">
    {% include 'girls/forms/review-form.html' %}
</div>
{% endif %}

{% endblock %}